version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm test -- --watchAll=false
  build: 
    commands: 
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'